services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    environment:
      - FLASK_ENV=production
      - FRONTEND_URL=http://localhost
      - DATABASE_URL=postgresql://user:password@db:5432/users_db
      - DOCUSIGN_SERVER_IP=http://195.110.34.168:5001/api
    secrets:
      - SECRET_KEY
      - ADMIN_MAIL
      - ADMIN_PASSWORD
      - DOCUSIGN_ACCOUNT_ID
      - DOCUSIGN_USER_ID
      - DOCUSIGN_INTEGRATION_KEY
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    volumes:
      - db_data:/app/instance
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
      args:
        - REACT_APP_BACKEND_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

volumes:
  db_data:
  postgres_data:

networks:
  default:
    driver: bridge

secrets:
  SECRET_KEY:
    file: ./.env_prod_secrets/SECRET_KEY
  ADMIN_MAIL:
    file: ./.env_prod_secrets/ADMIN_MAIL
  ADMIN_PASSWORD:
    file: ./.env_prod_secrets/ADMIN_PASSWORD
  DOCUSIGN_ACCOUNT_ID:
    file: ./.env_prod_secrets/DOCUSIGN_ACCOUNT_ID
  DOCUSIGN_USER_ID:
    file: ./.env_prod_secrets/DOCUSIGN_USER_ID
  DOCUSIGN_INTEGRATION_KEY:
    file: ./.env_prod_secrets/DOCUSIGN_INTEGRATION_KEY