services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    environment:
      - FLASK_ENV=production
      - FRONTEND_URL=https://localhost
      - BACKEND_URL=https://backend:5000
      - DATABASE_URL=postgresql://user:password@db:5432/users_db
      - DOCUSIGN_ENV=demo
      - DOCUSIGN_SERVER_IP=https://vps116574.serveur-vps.net//api
      - DOCUSIGN_PRIVATE_KEY_PATH=/run/secrets/DOCUSIGN_PRIVATE_KEY
    secrets:
      - SECRET_KEY
      - ADMIN_MAIL
      - ADMIN_PASSWORD
      - DOCUSIGN_ACCOUNT_ID
      - DOCUSIGN_USER_ID
      - DOCUSIGN_INTEGRATION_KEY
      - DOCUSIGN_PRIVATE_KEY
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    volumes:
      - db_data:/app/instance
      - ./backend/migrations:/app/migrations
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
      args:
        - REACT_APP_BACKEND_URL=/api
    expose:
      - "80"
    depends_on:
      - backend
    restart: always

  proxy:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

volumes:
  db_data:
  postgres_data:
  certbot-www:
  letsencrypt:

networks:
  default:
    driver: bridge

secrets:
  SECRET_KEY:
    file: ./.env_prod_secrets/SECRET_KEY.txt
  ADMIN_MAIL:
    file: ./.env_prod_secrets/ADMIN_MAIL.txt
  ADMIN_PASSWORD:
    file: ./.env_prod_secrets/ADMIN_PASSWORD.txt
  DOCUSIGN_ACCOUNT_ID:
    file: ./.env_prod_secrets/DOCUSIGN_ACCOUNT_ID.txt
  DOCUSIGN_USER_ID:
    file: ./.env_prod_secrets/DOCUSIGN_USER_ID.txt
  DOCUSIGN_INTEGRATION_KEY:
    file: ./.env_prod_secrets/DOCUSIGN_INTEGRATION_KEY.txt
  DOCUSIGN_PRIVATE_KEY:
    file: ./.env_prod_secrets/private.pem